services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: |
      # Locate and use the appropriate requirements file
      if [ -f requirements.txt ]; then
        pip install -r requirements.txt
      elif [ -f social_media_api/requirements.txt ]; then
        pip install -r social_media_api/requirements.txt
      else
        echo "No requirements.txt found"
        exit 1
      fi
    startCommand: gunicorn social_media_api.wsgi:application
    # rest of your configuration...