services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn social_media_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings_prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
    autoDeploy: true